### ISSUE TITLE
Bug: rollback doesn't always keep events, nor locations

### ISSUE THREAD

**Issue by StudioErrilhl** [langbakk/HSS#136]
Sometimes, when rolling back, the player will suddenly be in completely different locations

Also, during the shower-event with Juliette, rolling back might lead to the event not being available anymore. Should be kept.

**Comment by StudioErrilhl** [comment]
The user who reported this wasn't able to recreate the event, so this is currently on hold, till we get more information. We have not been able to recreate the event.

**Comment by langbakk** [comment]
Closing this, as not been able to reproduce
